version: '2'
services:
    imdesktopgateway-app:
        image: imdesktopgateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://imdesktopgateway-mysql:3306/im_desktop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8072:8072
    imdesktopgateway-mysql:
        extends:
            file: mysql.yml
            service: imdesktopgateway-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
